# Desenvolvimento 

# version: '3.8'

# services:
#   # Banco de Dados MySQL
#   db:
#     image: mysql:8.0
#     container_name: med_schedule_db
#     restart: always
#     environment:
#       MYSQL_DATABASE: med_schedule
#       MYSQL_ROOT_PASSWORD: root
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql

#   cache:
#     image: redis:alpine
#     container_name: med_schedule_cache
#     restart: always
#     ports:
#       - "6379:6379"

# volumes:
#   mysql_data:


# Produção
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: med_schedule_db
    restart: always
    environment:
      MYSQL_DATABASE: med_schedule
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  cache:
    image: redis:alpine
    container_name: med_schedule_cache
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: med_backend
    restart: always
    ports:
      - "3333:3333"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    # Roda as migrations e o seed do admin antes de subir o servidor
    command: >
      sh -c "npm run typeorm migration:run && 
             npm run seed:admin && 
             npm run dev"

  frontend:
    build: ./frontend
    container_name: med_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data: